// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cknnvkevckcgjvkombjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbm52a2V2Y2tjZ2p2a29tYmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzYzNTMsImV4cCI6MjA2OTYxMjM1M30.NygQ2TaHvdDbb3M2cnQBJ1DbxZ23oaHVhWSMaZZ1Edg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});